// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqniUUvY8zeR4qP5fu6zuPI9PynhdSCs',
    appId: '1:138494225706:web:697a5b051ac236e6f88253',
    messagingSenderId: '138494225706',
    projectId: 'chat-app-1de98',
    authDomain: 'chat-app-1de98.firebaseapp.com',
    storageBucket: 'chat-app-1de98.appspot.com',
    measurementId: 'G-23FCY8W7CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qY7Yg0ab8lumnCNMe-Bm3ydr486hfbs',
    appId: '1:138494225706:android:4c516a48bdef308ef88253',
    messagingSenderId: '138494225706',
    projectId: 'chat-app-1de98',
    storageBucket: 'chat-app-1de98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35aHO0-QVYIf_SXS1jcPr74QF9JrZY_E',
    appId: '1:138494225706:ios:fcd7e3c6443cfe67f88253',
    messagingSenderId: '138494225706',
    projectId: 'chat-app-1de98',
    storageBucket: 'chat-app-1de98.appspot.com',
    iosClientId: '138494225706-av25e349onej1tg43bdhan8g0k5rqoa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD35aHO0-QVYIf_SXS1jcPr74QF9JrZY_E',
    appId: '1:138494225706:ios:fcd7e3c6443cfe67f88253',
    messagingSenderId: '138494225706',
    projectId: 'chat-app-1de98',
    storageBucket: 'chat-app-1de98.appspot.com',
    iosClientId: '138494225706-av25e349onej1tg43bdhan8g0k5rqoa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
