// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5igH_Lt361AjLgh2ZgRrOhoHCxI5DwQ',
    appId: '1:531539051234:web:f25fd62ca8e6554dc9d4bb',
    messagingSenderId: '531539051234',
    projectId: 'bookapp-2f758',
    authDomain: 'bookapp-2f758.firebaseapp.com',
    storageBucket: 'bookapp-2f758.appspot.com',
    measurementId: 'G-TEZSJC4QG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqHEkKEfsXG7SazQ-liYVv0FtM2jljlE',
    appId: '1:531539051234:android:b8b39a6dad85fb56c9d4bb',
    messagingSenderId: '531539051234',
    projectId: 'bookapp-2f758',
    storageBucket: 'bookapp-2f758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflcN_QOTHknaappSlPjGpBq7Sknzv9Ps',
    appId: '1:531539051234:ios:2d3d666556bd9f3cc9d4bb',
    messagingSenderId: '531539051234',
    projectId: 'bookapp-2f758',
    storageBucket: 'bookapp-2f758.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflcN_QOTHknaappSlPjGpBq7Sknzv9Ps',
    appId: '1:531539051234:ios:c5c43582e336b14ec9d4bb',
    messagingSenderId: '531539051234',
    projectId: 'bookapp-2f758',
    storageBucket: 'bookapp-2f758.appspot.com',
    iosBundleId: 'com.example.bookStore.RunnerTests',
  );
}
